# Generated by Django 5.0.4 on 2024-04-21 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fights", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Urls",
            new_name="Url",
        ),
    ]
