# Generated by Django 5.0.4 on 2024-04-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fights", "0005_tourament"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Tourament",
            new_name="Tournament",
        ),
        migrations.RenameField(
            model_name="match",
            old_name="player1_name",
            new_name="player1_id",
        ),
        migrations.RenameField(
            model_name="match",
            old_name="player2_name",
            new_name="player2_id",
        ),
        migrations.RenameField(
            model_name="match",
            old_name="tournemant_name",
            new_name="tournament_name",
        ),
        migrations.RemoveField(
            model_name="match",
            name="match_time",
        ),
        migrations.AddField(
            model_name="match",
            name="match_id",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
