# Generated by Django 5.0.4 on 2024-04-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fights", "0014_match_match_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="updated_at",
            field=models.DateTimeField(null=True),
        ),
    ]
