# Generated by Django 5.0.4 on 2024-04-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fights", "0017_remove_match_suggested_play_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="suggested_play_order",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
