# Generated by Django 5.0.4 on 2024-08-01 18:14

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('preferences', '0003_alter_preferences_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyPreferences',
            fields=[
                ('preferences_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='preferences.preferences')),
                ('interleave_method', models.CharField(blank=True, default='Fixed', max_length=100, null=True)),
            ],
            bases=('preferences.preferences',),
            managers=[
                ('singleton', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('tournament_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('tournament_name', models.CharField(max_length=100)),
                ('tournament_state', models.CharField(max_length=100)),
                ('tournament_needs_interleave', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('url', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.CharField(blank=True, max_length=100, null=True)),
                ('participant_name', models.CharField(max_length=100, null=True)),
                ('tournament_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fights.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('match_state', models.CharField(max_length=100, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('suggested_play_order', models.IntegerField()),
                ('calculated_play_order', models.IntegerField(default=0)),
                ('estimated_start_time', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('underway_at', models.DateTimeField(blank=True, null=True)),
                ('player1_is_prereq_match_loser', models.BooleanField(default=False)),
                ('player2_is_prereq_match_loser', models.BooleanField(default=False)),
                ('player1_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='player1_id', to='fights.participant')),
                ('player2_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='player2_id', to='fights.participant')),
                ('tournament_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fights.tournament')),
            ],
        ),
        migrations.AddField(
            model_name='tournament',
            name='tournament_url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fights.url'),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(fields=('tournament_id', 'participant_id'), name='unique-in-field'),
        ),
    ]
