# Generated by Django 5.0.4 on 2024-05-08 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "tournament_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("tournament_name", models.CharField(max_length=100)),
                ("tournament_state", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Url",
            fields=[
                (
                    "url",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "participant_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("participant_name", models.CharField(max_length=100, null=True)),
                (
                    "tournament_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fights.tournament",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "match_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("match_state", models.CharField(max_length=100, null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("suggested_play_order", models.IntegerField()),
                (
                    "tournament_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fights.tournament",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="tournament",
            name="tournament_url",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="fights.url"
            ),
        ),
        migrations.AddConstraint(
            model_name="participant",
            constraint=models.UniqueConstraint(
                fields=("tournament_id", "participant_id"), name="unique-in-field"
            ),
        ),
    ]
