# Generated by Django 5.0.4 on 2024-05-08 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fights", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="player1_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="player1_id",
                to="fights.participant",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="player2_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="player2_id",
                to="fights.participant",
            ),
        ),
    ]
