# Generated by Django 5.0.4 on 2025-12-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fights", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mypreferences",
            name="interleave_method",
            field=models.CharField(
                choices=[("Fixed", "Fixed"), ("Interleave", "Interleave")],
                default="Fixed",
                max_length=100,
            ),
        ),
    ]
