# Generated by Django 5.0.4 on 2025-01-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fights", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mypreferences",
            name="interleave_method",
            field=models.CharField(default="Fixed", max_length=100),
        ),
    ]
