# Generated by Django 5.0.4 on 2025-04-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fights", "0002_tournament_tournament_repair_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="player1_prereq_match_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="player2_prereq_match_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
