# Generated by Django 5.0.4 on 2025-02-02 13:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fights', '0003_participant_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_timeout',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 7, 52, 58, tzinfo=datetime.timezone.utc)),
        ),
    ]
