# Generated by Django 5.0.4 on 2025-12-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fights", "0003_alter_mypreferences_interleave_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mypreferences",
            name="interleave_method",
            field=models.CharField(
                choices=[
                    ("Fixed", "Fixed"),
                    ("Interleave", "Interleave"),
                    ("Fixed_multiple", "Fixed_multiple"),
                    ("Interleave_multiple", "Interleave_multiple"),
                ],
                default="Fixed",
                max_length=100,
            ),
        ),
    ]
