# Generated by Django 5.0.4 on 2024-04-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fights", "0004_rename_matches_match"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tourament",
            fields=[
                (
                    "tournament_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("tournament_name", models.CharField(max_length=100)),
                ("tournament_state", models.CharField(max_length=100)),
            ],
        ),
    ]
