# Generated by Django 5.0.4 on 2024-05-29 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fights", "0004_tournament_tournament_needs_interleave"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="estimated_start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
