# Generated by Django 5.0.4 on 2024-12-24 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fights', '0004_alter_profile_last_timeout'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel("Participant", "Bot")
    ]