# Generated by Django 5.0.4 on 2024-05-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fights", "0005_alter_match_estimated_start_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="calculated_play_order",
            field=models.IntegerField(default=0),
        ),
    ]
