# Generated by Django 5.0.4 on 2025-02-02 13:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fights', '0005_rename_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bot',
            name='unique-in-field',
        ),
        migrations.RenameField(
            model_name='bot',
            old_name='participant_id',
            new_name='bot_id',
        ),
        migrations.RenameField(
            model_name='bot',
            old_name='participant_name',
            new_name='bot_name',
        ),
        migrations.AlterField(
            model_name='mypreferences',
            name='interleave_method',
            field=models.CharField(default='Fixed', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='bot',
            constraint=models.UniqueConstraint(fields=('tournament_id', 'bot_id'), name='unique-in-field'),
        ),
    ]
