# Generated by Django 5.0.4 on 2024-05-30 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fights", "0006_alter_match_calculated_play_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="underway_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
