# Generated by Django 5.0.4 on 2024-05-31 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fights", "0007_match_started_at_match_underway_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Options",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("interleave_type", models.IntegerField(default=0)),
            ],
        ),
    ]
