# Generated by Django 5.0.4 on 2024-04-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fights", "0007_remove_match_id_alter_match_match_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="match_id",
            field=models.CharField(
                default="Not Assigned",
                max_length=100,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
