# Generated by Django 5.0.4 on 2024-04-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fights", "0008_alter_match_match_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "participant_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("participant_name", models.CharField(max_length=100)),
                ("tournament_id", models.CharField(max_length=100)),
            ],
        ),
    ]
