# Generated by Django 5.0.4 on 2024-05-31 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fights", "0008_options"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Options",
            new_name="Option",
        ),
    ]
