# Generated by Django 5.0.4 on 2024-04-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fights", "0009_participant"),
    ]

    operations = [
        migrations.RenameField(
            model_name="match",
            old_name="tournament_name",
            new_name="tournament_id",
        ),
        migrations.AlterField(
            model_name="match",
            name="player1_id",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="match",
            name="player2_id",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
