# Generated by Django 5.0.4 on 2024-04-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fights", "0010_rename_tournament_name_match_tournament_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="match",
            name="match_id",
            field=models.CharField(default="Not Assigned", max_length=100),
        ),
    ]
