# Generated by Django 5.0.4 on 2024-04-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fights", "0011_match_id_alter_match_match_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="match_id",
            field=models.CharField(max_length=100),
        ),
    ]
