# Generated by Django 5.0.4 on 2024-06-26 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fights", "0012_mypreferences"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Option",
        ),
    ]
