# Generated by Django 5.0.4 on 2024-04-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fights", "0013_remove_match_id_alter_match_match_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="match_state",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
