# Generated by Django 5.0.4 on 2024-04-24 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fights", "0016_match_suggested_play_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="match",
            name="suggested_play_order",
        ),
    ]
